### ISSUE TITLE
Not connecting to exchange

### ISSUE THREAD

**Issue by orionjb2001** [jprochazka/adsb-exchange#16]
Hi, can't seem to connect.  Showing this error:
Sun Sep 11 18:23:01 2016 Lost connection to feed.adsbexchange.com:31090
Sun Sep 11 18:23:01 2016 Reconnecting in 30.0 seconds
Sun Sep 11 18:23:32 2016 Connected to multilateration server at feed.adsbexchange.com:31090, handshaking
Sun Sep 11 18:23:37 2016 Lost connection to feed.adsbexchange.com:31090
Sun Sep 11 18:23:37 2016 Reconnecting in 30.0 seconds

**Comment by orionjb2001** [comment]
Connected. :)

**Comment by jprochazka** [comment]
Generally when this happens its an issue server side. Thanks for reporting back!
