### ISSUE TITLE
mlat client from adsb-exchange feeder not feeding to port 30104

### ISSUE THREAD

**Issue by SAM26K** [jprochazka/adsb-exchange#18]
Hi,
Try as I may to edit the settings in "adsbexhange-mlat_maint.sh"  port 30104 is no longer feeding data beck from the mlat network.  I know I'm connected because I can see my feed on the sync matrix and connected with 10 nearby mlat receivers through the adsbexchange.

Is there a different port besides 30104 that adsb-exchange uses to feed back the mlat results?

**Comment by jprochazka** [comment]
Nope the port should remain as set. More than likely you encountered a hiccup on ADS-B Exchanges end.
