### ISSUE TITLE
Clarify mlat's altitude unit

### ISSUE THREAD

**Issue by kisenberg** [jprochazka/adsb-exchange#27]
In the setup-script, atitude (should be corrected to altitude) is requested from the user. It's not clear wich unit is in context.

"mlat-client -h" says: "Altitude of the receiver (height above ellipsoid).
                        Required. Defaults to metres, but units may specified
                        with a 'ft' or 'm' suffix. (Except if they're negative
                        due to option parser weirdness. Sorry!)"

Please add that information into the setup-script.

**Comment by TopBanana123** [comment]
This is still an issue on the current build
