### ISSUE TITLE
Choose which upload port

### ISSUE THREAD

**Issue by SiriusGen** [jprochazka/adsb-exchange#31]
ADSBx allows "custom feeds" by changing the default standard port from 30005 to another one which is free, and available from the Custom Feeds map.

Can you add an option during the install to allow the user to change the default port from 30005 to another of their choice?

**Comment by jprochazka** [comment]
Easy enough...
Ability to do so add a custom feed port added.
commit 2e5351371a283c882b4c7bc88999d685d2ff692c.
