### ISSUE TITLE
Bug in latest install script with custom feed port selection

### ISSUE THREAD

**Issue by MDA0803** [jprochazka/adsb-exchange#33]
Hi Joe
I found a bug in your latest install script with custom feed port selection. During install source port is changed to selected port number too. Please modify scripts leaving source unchanged in both mlat and netcat scripts. You can add  -d argument to first netcat call and -w 300 to second one
Marcin

**Comment by adsbxchange** [comment]
Improve the script to use socat :dancer: 

sudo apt-get install socat

nano /home/pi/adsb-exchange/adsbexchange-netcat_maint.sh

REMOVE

 /bin/nc 127.0.0..1 -d 30005 | /bin/nc -w 300 feed.adsbexchange.com:30005

REPLACE WITH
 
/bin/socat -u TCP:localhost:30005 TCPfeed.adsbexchange.com:30005

**Comment by jprochazka** [comment]
Thanks for catching that and sorry for the delay getting to it. I have merged your request into the master branch.
