### ISSUE TITLE
missing 2 required positional arguments: 'allow_anon' and 'allow_modeac'

### ISSUE THREAD

**Issue by eroom1966** [jprochazka/adsb-exchange#37]
Tried running the script ant the resultant adsbexchange-mlat_maint.sh, got the following error message

> Fri May 11 09:36:24 2018 mlat-client 0.2.10 starting up
> Traceback (most recent call last):
>   File "/usr/bin/mlat-client", line 101, in <module>
>     main()
>   File "/usr/bin/mlat-client", line 95, in main
>     coordinator = Coordinator(receiver=receiver, server=server, outputs=outputs, freq=options.clock_frequency(args))
> TypeError: __init__() missing 2 required positional arguments: 'allow_anon' and 'allow_modeac'
> 

looks like a missmatch between definition and usage of Coordinator()

Thx
Lee

**Comment by adsbxchange** [comment]
Use 0.2.6 .... not sure what is going on with 0.2.10
